# Base Image for executing jobs - contains Java and Android SDK with some additional libraries
# See https://github.com/jangrewe/gitlab-ci-android
image: jangrewe/gitlab-ci-android

# Define Gradle Home to use it for (optional) caching
before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Cache instruction - will save intermediate results for later jobs
# Might actually not speed up your pipeline runtime - just check it for yourself
#cache:
#  key: ${CI_PROJECT_ID}
#  paths:
#    - .gradle/

# Build Stages - release and deploy not used currently
stages:
  - build
  - test
  - docs

# Run detekt & klint checks
detekt:
  stage: build
  script:
    - ./gradlew
#    - ./gradlew -Pci --console=plain detekt
  artifacts:
    paths:
      - common/build/reports/detekt/detekt.*
      - app/build/reports/detekt/detekt.*
      - data/local/build/reports/detekt/detekt.*
      - data/remote/build/reports/detekt/detekt.*
      - data/repository/build/reports/detekt/detekt.*
      - domain/build/reports/detekt/detekt.*
      - feature/meal/build/reports/detekt/detekt.*
      - feature/recipe/build/reports/detekt/detekt.*
      - feature/shoppinglist/build/reports/detekt/detekt.*
      - feature/weeklist/build/reports/detekt/detekt.*
      - mocks/build/reports/detekt/detekt.*
      - usecases/build/reports/detekt/detekt.*
#  except:
#    changes:
#      - "**/*.md"


# Build a debug apk
assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
#  except:
#    changes:
#      - "**/*.md"

# Run Tests
testDebug:
  stage: test
  script:
    - ./gradlew -Pci --console=plain testDebug
  artifacts:
    reports:
      junit:
        - common/build/test-results/**/TEST-*.xml
        - app/build/test-results/**/TEST-*.xml
        - data/local/build/test-results/**/TEST-*.xml
        - data/remote/build/test-results/**/TEST-*.xml
        - data/repository/build/test-results/**/TEST-*.xml
        - domain/build/test-results/**/TEST-*.xml
        - feature/meal/build/test-results/**/TEST-*.xml
        - feature/recipe/build/test-results/**/TEST-*.xml
        - feature/shoppinglist/build/test-results/**/TEST-*.xml
        - feature/weeklist/build/test-results/**/TEST-*.xml
        - mocks/build/test-results/**/TEST-*.xml
        - usecases/build/test-results/**/TEST-*.xml
#  except:
#    changes:
#      - "**/*.md"

# Generate Docs via Dokka
generateDocs:
  stage: docs
  script:
    - ./gradlew dokkaHtmlMultiModule
  artifacts:
    paths:
      - build/dokkaMultiModuleOutput/**
#  except:
#    changes:
#      - "**/*.md"
